=== RobertBendun/history/schema.language.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "programmers-calendar/Language",
  "title": "Language",
  "description": "Definition of a programming language and it's releases",
  "type": "object",
	"additionalProperties": false,
	"required": [
		"name",
		"category",
		"releases"
	],
	"properties": {
		"name": {
			"description": "Name of programming language",
			"type": "string"
		},
		"category": {
			"description": "Category of document that this falls into",
			"type": "string",
			"enum": ["programming languages"]
		},
		"influenced_by": {
			"description": "Languages that influenced this programming language",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"website": {
			"description": "Link to programming language website",
			"type": "string"
		},
		"releases": {
			"description": "All releases of programming language",
			"type": "array",
			"items": {
				"type": "object",
				"additionalProperties": false,
				"required": [
					"version",
					"date",
					"features"
				],
				"properties": {
					"version": {
						"description": "Version identifier of this release",
						"type": "string"
					},
					"date": {
						"description": "Date of release",
						"type": "string"
					},
					"src": {
						"description": "Source of documentation about release",
						"type": "string"
					},
					"features": {
						"description": "Key features shipped with this realease",
						"type": "array",
						"items": {
							"type": "string"
						}
					}
				}
			}
		}
	}
}

=== RobertBendun/history/language.c.json
{
	"name": "C",
	"category": "programming languages",
	"website": "https://en.wikipedia.org/wiki/C_(programming_language)",
	"influenced_by": [
		"B",
		"ALGOL 68",
		"FORTRAN"
	],
	"releases": [
		{
			"version": "Included with Version 2 Unix",
			"date": "1972-06-12",
			"features": [
				"arrays",
				"char type",
				"pointers",
				"function return types"
			]
		},
		{
			"version": "K&R",
			"date": "1978-02-22",
			"features": [
				"added stdio library",
				"added long int type",
				"added unsigned int type",
				"moved from =op to op= for compound assigments"
			]
		}
	]
}

=== RobertBendun/history/language.go.json
{
	"name": "Go",
	"category": "programming languages",
	"influenced_by": [
		"APL",
		"Active Oberon",
		"Alef",
		"C",
		"Modula",
		"Newsqueak",
		"Oberon",
		"Oberon-2",
		"Pascal",
		"Smalltalk"
	],
	"website": "https://go.dev",
	"releases": [
		{
			"date": "2012-03-28",
			"version": "1.0",
			"src": "https://go.dev/doc/go1",
			"features": [
				"append builtin",
				"close channel builtin",
				"init routines can call goroutines",
				"rune type",
				"multiple assigment",
				"package hierarchy",
				"error type and errors package"
			]
		},
		{
			"version": "1.2",
			"date": "2013-12-01",
			"src": "https://go.dev/doc/go1.2",
			"features": [
				"thee-index slices allow to specify capacity of new slice",
				"pre-emption in the scheduler",
				"Cgo supports C++",
				"Test coverage",
				"encoding package adding xml, json and binary serialization"
			]
		},
		{
			"version": "1.3",
			"date": "2014-06-18",
			"src": "https://go.dev/doc/go1.3",
			"features": [
				"removed support for Windows 2000",
				"support for Plan 9",
				"Randomized iteration over small maps"
			]
		},
		{
			"version": "1.4",
			"src": "https://go.dev/doc/go1.4",
			"date": "2014-12-10",
			"features": [
				"for range loops without iteration variable",
				"Double pointer does not automatically dereference",
				"Translation of runtime to Go",
				"canonical import paths",
				"internal packages",
				"go generate"
			]
		},
		{
			"version": "1.5",
			"src": "https://go.dev/doc/go1.5",
			"date": "2015-08-19",
			"features": [
				"compiler and runtime entirely in Go",
				"concurrent garbage collector",
				"go tool trace",
				"go doc",
				"type ellision in map literals keys"
			]
		},
		{
			"version": "1.6",
			"src": "https://go.dev/doc/go1.6",
			"date": "2016-02-17",
			"features": [
				"automatic support for HTTP/2",
				"template reuse mechanism"
			]
		},
		{
			"version": "1.7",
			"src": "https://go.dev/doc/go1.7",
			"date": "2016-08-15",
			"features": [
				"context package",
				"hierarchies of tests and benchmarks",
				"vendoring support"
			]
		},
		{
			"version": "1.8",
			"src": "https://go.dev/doc/go1.8",
			"date": "2017-02-16",
			"features": [
				"structs that differ only in tags may be converted between each other",
				"backend using SSA",
				"default value for GOPATH",
				"sort.Slice function"
			]
		},
		{
			"version": "1.9",
			"src": "https://go.dev/doc/go1.9",
			"date": "2017-08-24",
			"features": [
				"type aliases",
				"parallel compilation",
				"monotonic time support",
				"math/bits, package for manipulating bits in efficient way",
				"concurrent map in sync package"
			]
		},
		{
			"version": "1.10",
			"src": "https://go.dev/doc/go1.10",
			"date": "2018-02-16",
			"features": [
				"default GOROOT and GOTEMPDIR",
				"caching in Go tools improvements"
			]
		},
		{
			"version": "1.11",
			"src": "https://go.dev/doc/go1.11",
			"date": "2018-08-24",
			"features": [
				"experimental port to WebAssembly",
				"experimental support of modules"
			]
		},
		{
			"version": "1.12",
			"src": "https://go.dev/doc/go1.12",
			"date": "2019-02-25",
			"features": [
				"go tour is no longer with binary distribution of Go",
				"support of TLS 1.3"
			]
		},
		{
			"version": "1.13",
			"src": "https://go.dev/doc/go1.13",
			"date": "2019-09-03",
			"features": [
				"binary integer literals with 0b prefix",
				"octal integer literals with 0o prefix",
				"hexadecimal floting-point literals",
				"imaginery literals",
				"digit separators using _",
				"support for error wrapping"
			]
		},
		{
			"version": "1.14",
			"src": "https://go.dev/doc/go1.14",
			"date": "2020-02-25",
			"features": [
				"module support ready for production use",
				"hash/maphash, hash functions for byte sequences"
			]
		},
		{
			"version": "1.15",
			"src": "https://go.dev/doc/go1.15",
			"date": "2020-08-11",
			"features": [
				"linker improvements for performance and maintability",
				"time/tzdata allows for inclusion of timezone database into binary"
			]
		},
		{
			"version": "1.16",
			"src": "https://go.dev/doc/go1.16",
			"date": "2021-02-16",
			"features": [
				"support for Apple Silicon architecture",
				"module-aware mode enabled by default",
				"//go:embed directive",
				"runtime/metrics, stable interface for implementation-defined metrics from Go runtime",
				"io/fs, abstraction for read-only trees of files",
				"io/ioutil deprecation"
			]
		},
		{
			"version": "1.17",
			"src": "https://go.dev/doc/go1.17",
			"date": "2021-08-16",
			"features": [
				"conversions from slice to array pointer",
				"support for 64-bit ARM on Windows"
			]
		},
		{
			"version": "1.18",
			"src": "https://go.dev/doc/go1.18",
			"date": "2022-03-15",
			"features": [
				"functions and type declarations with type parameters",
				"instantiation of parametrized types and functions with square brackets",
				"interface types allow for embeding types",
				"predefined any as shorthand for interface{}",
				"predefined comparable as shorthand for types that can be equality compared",
				"debug/buildinfo, giving access to module verions, version control information and build flags"
			]
		},
		{
			"version": "1.19",
			"src": "https://go.dev/doc/go1.19",
			"date": "2022-08-02",
			"features": [
				"new atomic types",
				"secure PATH lookups"
			]
		},
		{
			"version": "1.20",
			"src": "https://go.dev/doc/go1.20",
			"date": "2023-02-01",
			"features": [
				"conversions from slice to array",
				"suport for code coverage of all programs",
				"errors can wrap multiple errors"
			]
		},
		{
			"version": "1.21",
			"src": "https://go.dev/doc/go1.21",
			"date": "2023-08-08",
			"features": [
				"min and max builtins",
				"profile-guide optimization",
				"log/slog, a structured logging package",
				"slices, a generic slice operations package",
				"maps, a generic maps package",
				"cmp, generic functions related to comparisons package"
			]
		},
		{
			"version": "1.22",
			"src": "https://go.dev/doc/go1.22",
			"date": "2024-02-06",
			"features": [
				"new variable per each loop iteration",
				"loops over integer range",
				"math/rand/v2 (while keeping math/rand)",
				"enhanced builtin HTTP router with methods and wildcars"
			]
		},
		{
			"version": "1.23",
			"src": "https://go.dev/doc/go1.23",
			"date": "2024-08-13",
			"features": [
				"range over function types",
				"opt-in telemetry",
				"unique package providing intering",
				"iter package with support for iterators",
				"slices package extended with iterator support",
				"maps package extended with iterator support",
				"structs package that allow to change memory layout of structs"
			]
		},
		{
			"version": "1.24",
			"src": "https://go.dev/doc/go1.24",
			"date": "2025-02-11",
			"features": [
				"generic type aliases",
				"os.Root, a way to sandbox fs operations to specific directory",
				"weak package with weak pointers",
				"runtime.AddCleanup improves finalizers",
				"new crypto packages: mlkem, hkdf, pbkdf2, sha3"
			]
		},
		{
			"version": "1.25",
			"src": "https://go.dev/doc/go1.25",
			"date": "",
			"features": [
				"testing/synctest package introduced support for testing concurrent code",
				"container-awere GOMAXPROCS"
			]
		},
		{
			"version": "1.26",
			"src": "https://go.dev/doc/go1.26",
			"date": "",
			"features": [
				"new function now accepts expressions",
				"new Green Tea Garbage Collector",
				"new crypto/hpke package",
				"new experimental runtime/secret package"
			]
		}
	]
}
